### ISSUE TITLE
Support for dark theme?

### ISSUE THREAD

**Issue by dazza-codes** [ryanpcmcquen/workflowyCodeFormatter#10]
Is there an easy way to change the code styling to support a dark theme?  On a dark theme, the code text is too dark to be seen.

**Comment by ryanpcmcquen** [comment]
There is not at this time, but I would definitely accept a PR adding this.

**Comment by ryanpcmcquen** [comment]
@darrenleeweber, the latest version (`0.5.0`), which should arrive on your machine in the next day or so does offer an option _not_ to syntax highlight. It isn't exactly a dark theme, but it will keep the text from changing colors which will at least remove some of the ugliness.

To keep a code block from being syntax highlighted, simply do not specify a language, so:

    ```js

Becomes:

    ```

**Comment by ryanpcmcquen** [comment]
@dazza-codes, this is no longer an issue as syntax highlighting has been removed:
https://github.com/ryanpcmcquen/workflowyCodeFormatter#what-happened-to-syntax-highlighting
