### ISSUE TITLE
Option to turn off syntax highlighting?

### ISSUE THREAD

**Issue by tpantin** [ryanpcmcquen/workflowyCodeFormatter#11]
I love this tool, but I find that workflowy takes a performance hit when I have lots of code being formatted by this extension. I suspect this is coming from the syntax highlighting part. Any possibility that we might get an option to make code that is delimited solely with backticks (_i.e._, no language specified) not get any syntax highlighting? Would be particularly helpful when recording sequences of short bash commands, etc.

**Comment by ryanpcmcquen** [comment]
I like this idea. Let me see what I can put together ... conversely, a PR for this would be great. You could use single backticks in the interim.

**Comment by tpantin** [comment]
Fantastic. I wish my coding skills were up to snuff to make it likely that a PR from me would be worth your time to read. I was looking at prior release versions, though, before you incorporated syntax highlighting—was considering using one of those. 

Separately, are single backticks not supposed to trigger syntax highlighting? From my test, they seem to (see below).
![screen shot 2018-11-01 at 12 26 56 pm](https://user-images.githubusercontent.com/15853657/47865076-ade26980-ddd1-11e8-8ba8-4e581f7f08c9.png)

**Comment by ryanpcmcquen** [comment]
@tpantin, I started work on this, I think this change will fix it:
https://github.com/ryanpcmcquen/codeFormatter/commit/2cc17245b6d9ce8c5f2dfb90656fe45adc59e904

**Comment by ryanpcmcquen** [comment]
@tpantin, here is an example of how the new code removes the `PrettyPrint` specification:
https://repl.it/@ryanpcmcquen/MysteriousGrandPyramid

**Comment by tpantin** [comment]
Looks great! Thanks so much for this great tool.

**Comment by ryanpcmcquen** [comment]
@tpantin, happy to help! `0.5.0` has been published and should land on your machine in the next day or so.
