### ISSUE TITLE
Chrome store link down?

### ISSUE THREAD

**Issue by tpantin** [ryanpcmcquen/workflowyCodeFormatter#12]
Perhaps it's me, but it seems like the Chrome extension store link is broken, preventing me from installing the extension on a new computer: https://chrome.google.com/webstore/detail/workflowy-code-formatter/kglihipcanlbglgikjghocmbbbbkfemn

**Comment by ryanpcmcquen** [comment]
Weirdness, Google took it down and never contacted me. I have no idea why. I just emailed them. Thanks for the ping.

**Comment by ryanpcmcquen** [comment]
@tpantin, it has returned!
