### ISSUE TITLE
Syntax Highlighting not Working

### ISSUE THREAD

**Issue by MaxLinWorm** [ryanpcmcquen/workflowyCodeFormatter#17]
Hi,

Installed the extension, but can't get the syntax highlinghting to work. It only formats the text in a monospaced font.

On Chrome.

**Comment by ryanpcmcquen** [comment]
I'm sorry, I've added an explanation to the README:
https://github.com/ryanpcmcquen/workflowyCodeFormatter/blob/master/README.md#what-happened-to-syntax-highlighting

**Comment by ryanpcmcquen** [comment]
@MaxLinWorm, what do you think of this lib?
https://asvd.github.io/microlight/

**Comment by ryanpcmcquen** [comment]
Some examples of Microlight in action:
<img width="692" alt="Screen Shot 2020-07-17 at 3 29 33 PM" src="https://user-images.githubusercontent.com/772937/87835563-5ce30500-c842-11ea-8ff6-b72fea0796b7.png">
<img width="670" alt="Screen Shot 2020-07-17 at 3 29 41 PM" src="https://user-images.githubusercontent.com/772937/87835565-5d7b9b80-c842-11ea-8f0a-cc280ab295f3.png">

**Comment by ryanpcmcquen** [comment]
It's also language agnostic, so it doesn't matter what type of code you have.

**Comment by MaxLinWorm** [comment]
I'm just starting to learn coding, so I don't really have an opinion. I'd sure appreciate help in including code-prettify to the extension. =D

**Comment by ryanpcmcquen** [comment]
Syntax highlighting has been restored thanks to Microlight.
