### ISSUE TITLE
Can't Click on code to edit

### ISSUE THREAD

**Issue by dfrigon** [ryanpcmcquen/workflowyCodeFormatter#19]
Hi,

If i'm using it right, for multiline code, i have to use the note instead of multiple bullets. That being said, when I do so with the 3 back-ticks before and after, the text is formatted as code (in black and white though, not in colour) but if I want to edit that code by clicking in the code where I want to make that edit, the cursor jump and the beginning of the code.

The only way to edit is to write some character when it jump a the beginning to unformat it and then move with the arrows to where I want to really type, If I use the mouse it format the text again and jump me back to the beginning.

Thanks!

**Comment by ryanpcmcquen** [comment]
Yeah, multi line code is only expected in the note section, but, it sounds like we may need to fire the formatting less aggressively. What browser are you on?

**Comment by dfrigon** [comment]
I'm on Chrome Version 85.0.4183.121 (Official Build) (64-bit) on Mac

**Comment by ryanpcmcquen** [comment]
Would you be willing/have time to test a beta version that may alleviate this issue?

**Comment by dfrigon** [comment]
Yes of course!
Also, is it normal that there is no color formatting in the code?

**Comment by ryanpcmcquen** [comment]
@dfrigon, thank you! It's a long story, but most of the reasoning behind 'no color' is explained here:
https://github.com/ryanpcmcquen/workflowyCodeFormatter#what-happened-to-syntax-highlighting

**Comment by ryanpcmcquen** [comment]
@dfrigon, try this out:
https://github.com/ryanpcmcquen/workflowyCodeFormatter/archive/code_click_issue.zip

There are instructions here on how to side load a custom Chrome extension (**MAKE SURE TO DISABLE THE ORIGINAL!**):
https://www.cnet.com/how-to/how-to-install-chrome-extensions-manually/

**Comment by dfrigon** [comment]
@ryanpcmcquen, I get this error when loading the unpacked extension:

Failed to load extension
File
~/Downloads/workflowyCodeFormatter-code_click_issue
Error
Could not load javascript 'assets/codeFormatter/codeFormatter.js' for content script.
Could not load manifest.

**Comment by ryanpcmcquen** [comment]
@dfrigon, whoops, sorry about that, try this instead:

[workflowyCodeFormatter.zip](https://github.com/ryanpcmcquen/workflowyCodeFormatter/files/5335711/workflowyCodeFormatter.zip)

**Comment by dfrigon** [comment]
This solve the issue! Thank you!

**Comment by ryanpcmcquen** [comment]
@dfrigon, great, does everything else work well too? If so I will publish this as an update to the Chrome and Firefox stores.

**Comment by ryanpcmcquen** [comment]
@dfrigon, update submitted to Chrome and Firefox thingies!
