### ISSUE TITLE
Triple-backticked, multi-line code snippets 

### ISSUE THREAD

**Issue by NathanD-GDS** [ryanpcmcquen/workflowyCodeFormatter#23]
I don't seem to be able to get triple-backticked snippets to work for multi-line code. The documentation reads:

> Use [...] 3 backticks to wrap multi-line code. Note that the 3 backticks MUST be on their own line.

If I have the opening 3 backticks on their own line, then my content over X lines, then the closing backticks on their own line, formatting doesn't seem to apply.

Triple-backticked code only seems to work if the opening backticks, content, and closing backticks are contained in a single line. In this scenario, however, there doesn't seem to be a way to split the code over multiple lines.

![image](https://user-images.githubusercontent.com/80888259/117448295-7884dc80-af36-11eb-9669-1c5f53289b40.png)

**Comment by ryanpcmcquen** [comment]
The multi line code applies to 'notes', not bullet points or lists. WorkFlowy renders bullets as their own entity, which means I cannot format against that (also the bullets look weird and confusing inside of code, so I am not sure anyone would want that).

<img width="260" alt="Screen Shot 2021-05-07 at 6 41 54 AM" src="https://user-images.githubusercontent.com/772937/117458828-8e2adf80-aeff-11eb-8f5b-770df879f5ec.png">
<img width="202" alt="Screen Shot 2021-05-07 at 6 44 21 AM" src="https://user-images.githubusercontent.com/772937/117458940-ac90db00-aeff-11eb-8bda-8a5c895fddc7.png">
