### ISSUE TITLE
Paste?

### ISSUE THREAD

**Issue by terrisgit** [ryanpcmcquen/workflowyCodeFormatter#4]
I start text with ` and then command-v to paste in code. Each line of code ends up as a separate bullet point. The items are not formatted as code. Am I doing something wrong?

**Comment by ryanpcmcquen** [comment]
Hey @terrisgit, sorry you are having issues! Just a few questions so we can sort this out.
1. Where are you pasting the code from? (If you wouldn't mind, please paste it here between 3 backticks and see how it looks).
2. Are you closing the code with a backtick?

Also, just for reference, you should wrap things in 1 backtick for inline code (`inline code`)--code included in a sentence--and for large blocks use 3 backticks, like so:

```
function() {
  'use strict';
}());
```

**Comment by ryanpcmcquen** [comment]
Oh, and another thing ... WorkFlowy automatically formats multi-line pastes as a WorkFlowy list. You will want to use the 'Note' section for long code pastes.

![Add Note WorkFlowy](https://usercontent.irccloud-cdn.com/file/dBbrNYF1/addNoteWorkFlowy.gif)

Keyboard shortcut for adding notes is <kbd>shift</kbd> + <kbd>enter</kbd>.  :+1:

**Comment by terrisgit** [comment]
I needed the 'note' feature. Thanks!

**Comment by ryanpcmcquen** [comment]
You are most welcome!
