### ISSUE TITLE
Update to newer code-prettify

### ISSUE THREAD

**Issue by solson** [ryanpcmcquen/workflowyCodeFormatter#5]
Would it be possible to update based on the latest changes in https://github.com/google/code-prettify and put out a new release?

This extension already works pretty nicely for me, but it's lacking support for Rust which exists in the upstream code-prettify now and makes up the vast majority of my code snippets.

Thanks!

**Comment by ryanpcmcquen** [comment]
Hey @tsion, thanks for using the extension! Currently only JavaScript highlighting is supported, but I plan on reworking the highlighting for version `0.3.0` so that _```_ must occur on its own line. That will allow the language to be specified for multi block lines of code using code-prettify's `lang-*` syntax.

For JavaScript that would mean having a block like:

``````
```js
(function () {
  console.log('foo');
}());
```
``````

I'm not sure what the shortcut is for Rust, but it should all work, I plan the release for sometime this week. :wink:

**Comment by solson** [comment]
@ryanpcmcquen It seems to me that the language is being auto-detected, so for example I can enter C code and get lots of C-specific keywords highlighted in blue here:

![screenshot 2016-01-17 at 8 22 40 pm](https://cloud.githubusercontent.com/assets/26806/12381875/17e9ee86-bd58-11e5-825b-29bfc1d02ac8.png)

However, being able to explicitly specify the language would be awesome. You can't always trust auto-detection. The shortcut for Rust is <code>```rust</code>, by the way.

> I plan the release for sometime this week. :wink:

Looking forward to it. :smiley:

**Comment by ryanpcmcquen** [comment]
It certainly does look that way, but it is actually all being highlighted as JavaScript. :tada:

Most C-like languages highlight in a similar fashion. If you inspect the markup you will see `lang-js` inside of the `<code>` blocks. :+1:

I'm getting close to 0.3.0, but having an issue with it recognizing the language specification, the release could come as early as tomorrow. :smiley_cat:

Thanks again for the request, I thought Google was never going to update [code-prettify](https://github.com/google/code-prettify).

**Comment by ryanpcmcquen** [comment]
Looks like I may have finally gotten it:

![0 3 0wcf](https://cloud.githubusercontent.com/assets/772937/12423986/f01d4b38-be82-11e5-9caa-4667ee1c3ce6.png)

**Comment by solson** [comment]
Awesome, it seems to be working for me. Thanks for working on this!

**Comment by ryanpcmcquen** [comment]
Thanks for reporting, this gave me a good excuse to rewrite the regex as well (which I had been meaning to do). If you haven't already, please consider writing a review on the Chrome web store. :+1:
