### ISSUE TITLE
bug with russian words

### ISSUE THREAD

**Issue by jt3k** [ryanpcmcquen/workflowyCodeFormatter#6]
look 
![here](https://i.imgur.com/ZAJaF2g.png)
russian font is no monospaced
## 

for testing u can get this code-snipet

``` js
for(let i=0; i<5; i++) {
   //здесь i доступна
}
//здесь i не доступна
```

or this link https://workflowy.com/s/vZc2xfdy3h
## 

my system:
osx el-capitan
chrome 49.0.2623.87 (64-bit)
## 

I can provide any help for testing

**Comment by ryanpcmcquen** [comment]
Hi @jt3k, thanks for using the extension! It looks like the formatting is fine. What behavior are you expecting?

I put your comments in workflowy and it highlighted in the same way as English comments:

![screenshot-2016-03-18-at-11 09 09-compressor](https://cloud.githubusercontent.com/assets/772937/13887635/14f1b1c4-ecfa-11e5-8ca0-cd03534c5d45.png)

**Comment by jt3k** [comment]
hm.. then the problem is in default mono-spaced font in the browser 

in my default browser settings i look this ![](https://i.imgur.com/4bIDojd.png)

=> the "Courier"   font for monospaced text

---

I did some research, and I can say that the two fonts fit well

this font:, 
"Courier New"

![](https://i.imgur.com/eWVnfMT.png)

## 

this my research:
I created a test page with multiple blocks with mono-spaced font http://jsbin.com/xutikoqeti

in different browsers it looks like this

## IE9

![](https://i.imgur.com/SE1dZjw.png)

## Firefox 44.0.2

![](https://i.imgur.com/2aqVjJR.png)

## Chrome 49.0.2623...

![](https://i.imgur.com/QUrWivt.png)

---

On these screenshots we can see that the most suitable mono-spaced font is courier-new

Let's make it to be default font in workflowyCodeFormatter ?

**Comment by ryanpcmcquen** [comment]
workflowyCodeFormatter does not set the font (and I don't think it should), that part actually comes from Google's [code-prettify](https://github.com/google/code-prettify). You are welcome to open the issue there.

**Comment by jt3k** [comment]
lol ok

**Comment by ryanpcmcquen** [comment]
Oops, I mis-spoke. This is actually set by the Browser/OS. We aren't likely to find a solution that works well across all platforms. Sorry if this causes any trouble, but you should set your monospace font at the system level to alleviate this issue.

**Comment by jt3k** [comment]
@ryanpcmcquen it is really so.
but code-prettify allows you to customize the font using styles.
Why don't you do it

**Comment by jt3k** [comment]
bump-up, and re-open issue

**Comment by ryanpcmcquen** [comment]
Adding a font-setting capability would mean having some kind of front-facing options menu. I really don't want to get in to that because it would add a _lot_ of complexity to the code of this extension.

If you want to put together a pull request I will take a look, but honestly I don't think the font should be set by this extension.

**Comment by ryanpcmcquen** [comment]
You would probably be really happy using this extension in conjunction with workflowyCodeFormatter:

https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en

**Comment by jt3k** [comment]
looks good ) thnx
