### ISSUE TITLE
Not working in Chrome App

### ISSUE THREAD

**Issue by tiernanmartin** [ryanpcmcquen/workflowyCodeFormatter#8]
Sorry for the vague issue title.

I installed the extension in Chrome, closed the browser, and then opened a new browser window and fired up Workflowy.

My backtick-enclosed text still looks like this:

![workflowy-test](https://user-images.githubusercontent.com/8197328/27147126-7bcbc492-50f0-11e7-8a94-daf6a5d39af5.PNG)

I double-checked and the extension is definitely enabled. What am I doing wrong here?

**Comment by ryanpcmcquen** [comment]
It is still working for me ... do you have some kind of theme enabled?

**Comment by tiernanmartin** [comment]
No Chrome themes - is that what you mean?

I've got both extensions enabled - is there some additional step I need to take to activate it?
![wf-2](https://user-images.githubusercontent.com/8197328/27148219-538de8a8-50f4-11e7-9a22-c9c055d87077.PNG)

**Comment by ryanpcmcquen** [comment]
Are you running WorkFlowy in a browser tab or with the Chrome 'App'?

**Comment by tiernanmartin** [comment]
Chrome App. Just checked and it works great in the browser. 

Now that we know what's going on, would you like me to edit the title of the issue to better reflect this problem?

**Comment by ryanpcmcquen** [comment]
Unfortunately Chrome extensions do not work inside of Chrome Apps, as much as I would like to fix it, within the current landscape of Chrome extensions, it will not be possible.

**Comment by tiernanmartin** [comment]
Got it – thanks for explaining that. 

Since that Apps-Extensions limitation is probably not common knowledge to the average Workflowy user, you might consider adding it to the documentation somewhere just in case some else repeats my experience.

**Comment by ryanpcmcquen** [comment]
@tiernanmartin, good thinking, I added a note to the README here and on the Chrome web store.
