### ISSUE TITLE
Specified language not being detected.

### ISSUE THREAD

**Issue by aneuhold** [ryanpcmcquen/workflowyCodeFormatter#9]
It seems that using 3 backticks isn't working for some reason. I can't seem to find out why. I don't have too much experience with front end development so sorry I can't be of more help in deducing what is happening here. 1 backtick works fine, but the 3 ticks with language specific formatting would be very awesome to have. 

Here is a screenshot of what happens when attempting to use the 3 back ticks in a note on workflowy: 
![capture](https://user-images.githubusercontent.com/17774559/38649352-ec53d7c0-3daa-11e8-851c-10940324081f.PNG)

All extensions have been disabled, and so has extra css formatting in attempts at troubleshooting this. This is on chrome 65.0.3325.181.

**Comment by ryanpcmcquen** [comment]
@aneuhold, that looks like syntax highlighting with a monospaced font to me ...

**Comment by aneuhold** [comment]
@ryanpcmcquen , Yes lol that seems to be correct. The single back ticks are working correctly. This is HTML code with the HTML identifier after the first three backticks but it is being formatted like JavaScript.

**Comment by aneuhold** [comment]
Do the 3 backticks work for you currently @ryanpcmcquen? Here is what is going on in that exact space on the page: 
![capture](https://user-images.githubusercontent.com/17774559/38652851-a74da63a-3dbc-11e8-84f0-e8647b0b9bc5.PNG)

**Comment by ryanpcmcquen** [comment]
I've reproduced the problem and am working on a fix.

**Comment by aneuhold** [comment]
Thank you!!

**Comment by ryanpcmcquen** [comment]
@aneuhold, `0.4.3` is out, would you mind updating to see if it resolves the issue?

**Comment by aneuhold** [comment]
Just tried to update, haven't had enough time to see how to fix the issue yet, but this is whats coming up after trying to install the extension: 
![image](https://user-images.githubusercontent.com/17774559/38825540-cc1a6130-4161-11e8-8d87-c996afca0e95.png)
Chrome 65.0.3325.181 on MacOS Sierra 10.12.6

**Comment by ryanpcmcquen** [comment]
Darnit, I forgot to include the assets, will fix that in a minute.

**Comment by ryanpcmcquen** [comment]
OK, `0.4.4` has uploaded and should be available soon. Sorry for the trouble.

**Comment by aneuhold** [comment]
No problem at all man, this extension is free and it takes time to program these things. Thank you so much for the support!

**Comment by aneuhold** [comment]
It seems to be working now. Thank you!

**Comment by ryanpcmcquen** [comment]
Woot! Thanks for following up @aneuhold!
